apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bubble-animation/application-mainfest
    repoURL: https://github.com/KadirvelA/ocp-2.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false